[build]
  publish = "."

[[redirects]]
  from = "//www.calculator.dentalspace.pro/*"
  to = "//calculator.dentalspace.pro/:splat"
  status = 301
  force = true

[[forms]]
  name = "contact"
  settings = { recipients = ["expert@dentalspace.pro"] }

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
